services:
  web:
    depends_on:
      - api
    build:
      context: .
      dockerfile: Dockerfile
    image: adw3r-tech-site:latest
    ports:
      - "443:443"
    restart: unless-stopped
    environment:
      - NODE_ENV=production

  api:
    restart: unless-stopped
    container_name: api
    build: ./api
    image: adw3r-tech-api:latest
    ports:
      - "3000:3000"
